table RLS
	lineageTag: 9681ce58-ce8e-4a9d-8b43-b1b49fb6066a

	column idVendedor
		dataType: int64
		formatString: 0
		lineageTag: 1e4644b5-5748-41d2-959a-31f39e6db243
		summarizeBy: sum
		sourceColumn: idVendedor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mail
		dataType: string
		lineageTag: 356f94d1-9d58-4350-9570-26c1d31615f9
		summarizeBy: none
		sourceColumn: mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rol
		dataType: string
		lineageTag: d1c6e831-1470-4373-abc0-07b9c8eb8d4c
		summarizeBy: none
		sourceColumn: Rol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition RLS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pZU9T8MwEIb/S+aqymdJNpDowAADiCmqkHGOciixW3906K/HEUvPQVGvGa340b2+971L2yZZmiar5AAddtre934vrPjUBuwabPjw/rZ9TXarNmmKcJJ6ACNR9B/OgITL6wHQakBptNVfbh1uXtJlSWjl4cSgiztCSy+c0dfjNZWuFUd5sSFwhyCRKX9TVOHoBmEcKjhPm/zw+Pz08ldtNKMTCqGfu9ZQUUePrDflYz+3yuDRw4zlWT19ukVwjEpNRZ0TThtW9zPCW0DLeGYeR5YBZ+lY+scLdcC5HqVjkV7v0TqUYm6AqJpOs/oQRVh+M/KfpwT2isEWVDXT/rr6J0E8DxsaoBB0hvpykuAzo3QWGcaQXdONdQJULl6wV8zozRszbvwC7Sw2XhkcNsr4sn8Eq3K0Tnk+xWN9e7iZwxWNNXczF4voagkd/VM59O4X", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [idVendedor = _t, mail = _t, Rol = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"idVendedor", Int64.Type}, {"mail", type text}, {"Rol", type text}}),
				    #"Filas ordenadas" = Table.Sort(#"Tipo cambiado",{{"idVendedor", Order.Ascending}})
				in
				    #"Filas ordenadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

