table RLS
	lineageTag: 9681ce58-ce8e-4a9d-8b43-b1b49fb6066a

	column idVendedor
		dataType: int64
		formatString: 0
		lineageTag: 1e4644b5-5748-41d2-959a-31f39e6db243
		summarizeBy: sum
		sourceColumn: idVendedor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mail
		dataType: string
		lineageTag: 356f94d1-9d58-4350-9570-26c1d31615f9
		summarizeBy: none
		sourceColumn: mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rol
		dataType: string
		lineageTag: d1c6e831-1470-4373-abc0-07b9c8eb8d4c
		summarizeBy: none
		sourceColumn: Rol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: 39990909-36c6-4740-a00b-9368cdc22ab5
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition RLS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pVbLTsMwEPyXnCuUR9MmN5DogQMcQJyqChnHlEWp3frRQ78exweEXdTu4lMiZXa8j9lx1uuiKstiVuzFAIMyt6PbMsPelRbmRhj/4fVl9ewfxWa2LvrGv3G1E5oDG9+sFlz8jvAxSu6Aa2XUh73xyIRgPo8IpBNHGkGzjAi4Y1YrEkMX16AksYRmEcUPIDjQ61g0rX+1O6YtSHE6b/vd/ePD08+Z04QGJkGMV5B9nN3BAbW+eurwSmo4OHFZDVV33gkDwtLO69t4oswqTR1JFVEYAYZWcp3KmhZflVMCX47JPVxpWTkdNaotGAucXdm2OK1BUduSKJ1/0jalLqN4J2nhTZw+XRld+4e+yLPtY3n5faCVMT9T+YmWQJVMkZZ/FxveUYC0qVHjdjrHdtNR5BVBDU+Nhhie7EH2pUM9P/Fk8vBSG8haAPoaJjbwD4dvcgnaTILkzqYTBAVK56/ry5Ydlh2Dq5G4JQ4XJI7Ahf8vDB/y3OALGBySL6wKpi+TJkELeeUXJYgfgQt3FQa3QOI6JA6ZX1gh7LlZm5LlFptv", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [idVendedor = _t, mail = _t, Rol = _t, Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"idVendedor", Int64.Type}, {"mail", type text}, {"Rol", type text}}),
				    #"Filas ordenadas" = Table.Sort(#"Tipo cambiado",{{"idVendedor", Order.Ascending}, {"mail", Order.Ascending}}),
				    #"Filas filtradas" = Table.SelectRows(#"Filas ordenadas", each true)
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

