table RLS
	lineageTag: 9681ce58-ce8e-4a9d-8b43-b1b49fb6066a

	column idVendedor
		dataType: int64
		formatString: 0
		lineageTag: 1e4644b5-5748-41d2-959a-31f39e6db243
		summarizeBy: sum
		sourceColumn: idVendedor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mail
		dataType: string
		lineageTag: 356f94d1-9d58-4350-9570-26c1d31615f9
		summarizeBy: none
		sourceColumn: mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rol
		dataType: string
		lineageTag: d1c6e831-1470-4373-abc0-07b9c8eb8d4c
		summarizeBy: none
		sourceColumn: Rol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Usuario
		dataType: string
		lineageTag: 737babe8-b187-44a9-84b3-14ed2cd47acf
		summarizeBy: none
		sourceColumn: Usuario

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Licencia'
		dataType: string
		lineageTag: 47f0d2c4-b2cc-43c2-a84e-d522f47a6efc
		summarizeBy: none
		sourceColumn: Tipo de Licencia

		annotation SummarizationSetBy = Automatic

	partition RLS = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Plg-obJNoVLw4UkWKZMwQRSboYI4avX0Cxm_yc778Os/edit?gid=0#gid=0"),
				    Personalizado1 = Origen{[name="RLS",ItemKind="Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Personalizado1, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"idVendedor", Int64.Type}, {"mail", type text}, {"Rol", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

