table RLS
	lineageTag: 7d96a8d9-e77c-4f45-aa6b-e08eb8b37950

	column idVendedor
		dataType: int64
		formatString: 0
		lineageTag: 7532ecc4-923e-4cd5-844a-3bae9ea22afa
		summarizeBy: sum
		sourceColumn: idVendedor

		annotation SummarizationSetBy = Automatic

	column mail
		dataType: string
		lineageTag: dfc55067-56eb-47f2-9411-bcb83b6158d2
		summarizeBy: none
		sourceColumn: mail

		annotation SummarizationSetBy = Automatic

	column Rol
		dataType: string
		lineageTag: d462d957-041c-49e1-9d93-41bf99c5bcc5
		summarizeBy: none
		sourceColumn: Rol

		annotation SummarizationSetBy = Automatic

	partition RLS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjJU0lFKzs9NLUrOTMyJT8kvdsgpTU8sTkzKL0otTi3WA8oBVTi6+Hr6KcXqRCsZGwC5KbmJRSWZealVyIr1UotRVJoZmwL5JQSVxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [idVendedor = _t, mail = _t, Rol = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"idVendedor", Int64.Type}, {"mail", type text}, {"Rol", type text}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado","comercial_dos@lugasaboreses.com","comercial_dos@lugasaboreses.onmicrosoft.com",Replacer.ReplaceText,{"mail"})
				in
				    #"Valor reemplazado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

