DEFINE
	VAR __DS0FilterTable = 
		TREATAS({2026}, 'Calendario'[Año])

	VAR __DS0FilterTable2 = 
		TREATAS({"Si"}, 'Modo Comparación'[Modo])

	VAR __DM3FilterTable = 
		TREATAS({""}, 'Clientes'[nomCom])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				'Clientes'[nomCom], "IsGrandTotalRowTotal",
				'Clientes'[idCliente], "IsDM1Total", NONVISUAL(__DM3FilterTable)
			),
			__DS0FilterTable,
			__DS0FilterTable2,
			"CountidCliente", CALCULATE(COUNTA('Clientes'[idCliente])),
			"Estado_Cliente", 'Métricas Clientes'[Estado Cliente],
			"DistinctCountidAlb", CALCULATE(DISTINCTCOUNT('FactVentas'[idAlb])),
			"Media_Albarán", 'MétricasVentas'[Media Albarán],
			"Referencias_Distintas_AA", 'Métricas Producto'[Referencias Distintas AA],
			"Referencias_Distintas", 'Métricas Producto'[Referencias Distintas],
			"Color_Media_Referencias", IGNORE('Métricas Visuales'[Color Media Referencias])
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			502,
			__DS0Core,
			[IsGrandTotalRowTotal],
			0,
			'Clientes'[nomCom],
			1,
			[IsDM1Total],
			0,
			'Clientes'[idCliente],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC,
	'Clientes'[nomCom],
	[IsDM1Total] DESC,
	'Clientes'[idCliente]